server:
  port: 8100

spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

zuul:
  routes:
    personservice:
      serviceId: person-service
    cartservice:
      serviceId: product-service
